os: linux
dist: xenial
python: 3.9
language: python
jobs:
  include:
    - name: "Python 3.9.0 on Linux"
      python: 3.9
    - name: "Python 3.9.0 on MacOS"
      os: osx
      osx_image: xcode12.2
      language: shell
before_install:
  - python3 --version
  - python3 -m pip install --upgrade pip
install:
  - pip3 install -r requirements.txt
script: make test
after_success: bash <(curl -s https://codecov.io/bash)
