codecov:
  branch: main
  require_ci_to_pass: true

coverage:
  precision: 2
  round: nearest

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

fixes:
  - "/home/travis/build/GreaterGoodCorp/::"
